/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Blender(props) {
  const { nodes, materials } = useGLTF('/Blender.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.GreyMetalic}
        position={[0, 1.004, 0]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[-0.903, 0, 0.879]}
        scale={0.143}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[0.871, 0, 0.879]}
        scale={0.143}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[-0.903, 0, -0.895]}
        scale={0.143}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[0.871, 0, -0.895]}
        scale={0.143}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials.BlackPlastic}
        position={[0.013, 0.645, -1.165]}
        rotation={[-1.463, 0, 0]}
        scale={[0.192, 0.037, 0.192]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials['Material.001']}
        position={[0, 2.957, -0.01]}
        scale={[0.767, 1.004, 0.767]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.BlackPlastic}
        position={[-1.313, 3.028, 0]}
        scale={[0.355, 0.095, 0.131]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials.BlackPlastic}
        position={[-0.871, 3.969, -0.006]}
        rotation={[0, 0, 1.527]}
        scale={[0.877, 0.139, 0.877]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.BlackPlastic}
        position={[0, 1.004, 0]}
        rotation={[0, Math.PI / 2, 0]}
      />
    </group>
  )
}

useGLTF.preload('/Blender.glb')