/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useLoader } from "@react-three/fiber";
import { RepeatWrapping, TextureLoader,  } from "three";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/factory.glb");
  const { actions } = useAnimations(animations, group);
  const shaderMat = useRef()
  useEffect(() => {
    actions["Cube.007Action"].play();
    actions["Cube.008Action"].play();
  }, [actions]);
  const line = useLoader(TextureLoader, "/treadmill.png")
  line.wrapS = RepeatWrapping
  line.wrapT = RepeatWrapping
  line.magFilter = 1003
  line.minFilter = 1003
  line.repeat.set(10,50)
  useFrame((state) => {
    line.offset.x += 0.2; // Adjust the speed and direction of animation
    line.offset.y += 0.2;

    // Ensure values stay within [0, 1] range for repeat wrapping
    if (line.offset.x > 1) line.offset.x -= 1;
    if (line.offset.y > 1) line.offset.y -= 1;

  })
  return (
    <group ref={group} {...props} dispose={null}>
    <group name="Scene">
    <mesh
    name="Cube"
    castShadow
    receiveShadow
    geometry={nodes.Cube.geometry}
    material={materials.Material}
    position={[0, 2.726, 0]}
    scale={[1.449, 1, 1.246]}
    />
    <mesh
    name="Cylinder"
    castShadow
    receiveShadow
    geometry={nodes.Cylinder.geometry}
    material={materials.Cog}
    position={[0, 1.305, -2.544]}
    rotation={[-Math.PI, 0, -Math.PI / 2]}
    scale={[-0.304, -1.116, -0.304]}
    />
    <mesh
      name="Plane"
      castShadow
      receiveShadow
      geometry={nodes.Plane.geometry}
      material={materials.Track}
      position={[0, 1.664, -6.742]}
      scale={[1, 1, 7.187]}
    >
    <meshBasicMaterial map={line}/>
    </mesh>
    <mesh
    name="Cylinder001"
    castShadow
    receiveShadow
    geometry={nodes.Cylinder001.geometry}
    material={materials.Cog}
    position={[0, 1.285, -1.535]}
    rotation={[-Math.PI, 0, -Math.PI / 2]}
    scale={[-0.364, -1.012, -0.364]}
    />
    <mesh
    name="Cylinder002"
    castShadow
    receiveShadow
    geometry={nodes.Cylinder002.geometry}
    material={materials.Cog}
    position={[0, 1.501, -1.977]}
    rotation={[-Math.PI, 0, -Math.PI / 2]}
    scale={[-0.161, -0.977, -0.161]}
    />
    <mesh
    name="Cylinder003"
    castShadow
    receiveShadow
    geometry={nodes.Cylinder003.geometry}
    material={materials.Stand}
    position={[0, 1.285, -13.678]}
    rotation={[-Math.PI, 0, -Math.PI / 2]}
    scale={[-0.364, -1.012, -0.364]}
    />
    <mesh
    name="Cylinder004"
    castShadow
    receiveShadow
    geometry={nodes.Cylinder004.geometry}
    material={materials.Cog}
    position={[0, 1.516, -13.227]}
    rotation={[-Math.PI, 0, -Math.PI / 2]}
    scale={[-0.161, -0.977, -0.161]}
    />
    <mesh
    name="Cube002"
    castShadow
    receiveShadow
    geometry={nodes.Cube002.geometry}
    material={materials.Stand}
    position={[0, 1.321, -7.587]}
    scale={[1, 0.35, 0.066]}
    />
    <mesh
    name="Cube003"
    castShadow
    receiveShadow
    geometry={nodes.Cube003.geometry}
    material={materials.UpperCan}
    position={[0, 2.726, 0]}
    scale={[1.449, 1, 1.246]}
    />
    <mesh
    name="Cube004"
    castShadow
    receiveShadow
    geometry={nodes.Cube004.geometry}
    material={materials.Stand}
    position={[0, 0.482, -13.505]}
    scale={[1, 0.397, 0.309]}
    />
    <mesh
    name="Cube001"
    castShadow
    receiveShadow
    geometry={nodes.Cube001.geometry}
    material={materials.Stand}
    position={[0, 1.321, -7.842]}
    scale={[1, 0.35, 0.066]}
    />
    <mesh
    name="Cube005"
    castShadow
    receiveShadow
    geometry={nodes.Cube005.geometry}
    material={materials.Inner}
    position={[0, 2.748, -0.048]}
    scale={[1.449, 1, 1.246]}
    />
    <mesh
    name="Cube006"
    castShadow
    receiveShadow
    geometry={nodes.Cube006.geometry}
    material={materials.Stand}
    position={[0, 0.482, -2.816]}
    scale={[1, 0.397, 0.309]}
    />
    <mesh
    name="Cube007"
    castShadow
    receiveShadow
    // geometry={nodes.Cube007.geometry}
    material={materials.Rails}
    position={[0, 1.791, 14.047]}
    scale={[0, 0, 0]}
    />
    <mesh
    name="Cube008"
    castShadow
    receiveShadow
    geometry={nodes.Cube008.geometry}
    material={materials.Box}
    position={[0, 2.444, -0.399]}
    rotation={[-0.003, 0, 0]}
    scale={0.424}
    >
    <mesh
    name="Plane001"
    castShadow
    receiveShadow
    geometry={nodes.Plane001.geometry}
    material={materials.Logo}
    position={[1.042, 0, -0.046]}
    rotation={[1.57, 0, -Math.PI / 2]}
    scale={0.482}
    />
    </mesh>
    <group
    name="GearFullVersion_Applied004"
    position={[-1.123, 1.295, -13.596]}
    rotation={[-0.089, 0, -Math.PI / 2]}
    scale={5.426}
    >
    <mesh
    name="Plane011"
    castShadow
    receiveShadow
    geometry={nodes.Plane011.geometry}
    material={materials.Metal_rough}
    />
    <mesh
    name="Plane011_1"
    castShadow
    receiveShadow
    geometry={nodes.Plane011_1.geometry}
    material={materials["Metal_rough.Darker"]}
    />
    <mesh
    name="Plane011_2"
    castShadow
    receiveShadow
    geometry={nodes.Plane011_2.geometry}
    material={materials["Metal_rough.Golden"]}
    />
    </group>
    <group
    name="GearFullVersion_Applied003"
    position={[1.128, 1.323, -13.626]}
    rotation={[-2.82, 0, Math.PI / 2]}
    scale={6.248}
    >
    <mesh
    name="Plane010"
    castShadow
    receiveShadow
    geometry={nodes.Plane010.geometry}
    material={nodes.Plane010.material}
    />
    <mesh
    name="Plane010_1"
    castShadow
    receiveShadow
    geometry={nodes.Plane010_1.geometry}
    material={materials.Metal_rough}
    />
    <mesh
    name="Plane010_2"
    castShadow
    receiveShadow
    geometry={nodes.Plane010_2.geometry}
    material={materials["Metal_rough.Golden"]}
    />
    <mesh
    name="Plane010_3"
    castShadow
    receiveShadow
    geometry={nodes.Plane010_3.geometry}
    material={materials["Metal_rough.Darker"]}
    />
    </group>
    <group
    name="GearFullVersion_Applied002"
    position={[-0.157, 0.216, -0.988]}
    rotation={[1.737, 0, -Math.PI / 2]}
    >
    <mesh
    name="Plane009"
    castShadow
    receiveShadow
    geometry={nodes.Plane009.geometry}
    material={materials.Metal_rough}
    />
    <mesh
    name="Plane009_1"
    castShadow
    receiveShadow
    geometry={nodes.Plane009_1.geometry}
    material={materials["Metal_rough.Darker"]}
    />
    </group>
    </group>
    </group>
  );
}

useGLTF.preload("/factory.glb");
